# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "db105bac55c1cec86da2e89f9e5e8132"
name = "quantity"
handle = "quantity-5"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "learn123456.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,unauthenticated_read_product_inventory"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
